### ISSUE TITLE
how to get funds from contract

### ISSUE THREAD

**Issue by Sanbingo** [ac12644/Fundraiser_Dapp#1]
how to get funds from contract

**Comment by Sanbingo** [comment]
home.js not complete work

**Comment by ac12644** [comment]
You can find it in [FundraiserCard.js](https://gist.github.com/ac12644/3c38f7d7594f91f9d42a55d3c9905139#file-fundraisercard-js) from line 238-247.

**Comment by Sanbingo** [comment]
> You can find it in [FundraiserCard.js](https://gist.github.com/ac12644/3c38f7d7594f91f9d42a55d3c9905139#file-fundraisercard-js) from line 238-247.
