### ISSUE TITLE
Error: Could not find artifacts for SimpleStorage from any sources

### ISSUE THREAD

**Issue by stobbsc** [ac12644/Fundraiser_Dapp#3]
I keep getting the error on the migration section.

It throws the above error for the SimpleStorage, which seems right, but then when I change it to say Funderaise then the construct is expection 6 parameters but the file passes none?

Is anyone else seeing this?

**Comment by ac12644** [comment]
Thank you for pointting out error. You can remove SimpleStorage part from 2_factory_contract_migrations.js, it's not required
<img width="813" alt="Screenshot 2022-06-01 at 12 40 32" src="https://user-images.githubusercontent.com/43683452/171386255-16a1d1a3-8181-4b03-b534-33f3ba6d3c1f.png">
.

**Comment by ac12644** [comment]
Did it resolve the problem? Otherwise, I am going to close this issue.

**Comment by stobbsc** [comment]
RESOLVED
